TRANSLATIONS = {
    "English": {
        "Soil Type": "Soil Type",
        "Moisture": "Moisture",
        "Confidence": "Confidence",
        "Duration": "Duration",
        "Recommendation": "Recommendation",
        "Soil Metrics": "Soil Metrics",
        "Feature Graphs": "Feature Graphs",
        "AI Recommendations": "AI Recommendations",
        
        "Compact Soil": "Compact Soil",
        "Dry Soil": "Dry Soil",
        "Healthy Soil": "Healthy Soil",
        "High": "High",
        "Moderate": "Moderate",
        "Low": "Low",
        "Optimal": "Optimal",
        
        "⚠ Soil Aeration Recommended": "⚠ Soil Aeration Recommended",
        "💧 Soil Irrigation Needed": "💧 Soil Irrigation Needed",
        "✅ Soil Condition Stable & Good": "✅ Soil Condition Stable & Good",
        
        "recs_compact": "- Add organic compost to loosen texture and introduce bio-matter\n- Improve field drainage channels to prevent waterlogging\n- Avoid heavy machinery usage during high moisture days\n- Re-sample and monitor soil moisture after 3 days",
        "recs_dry": "- Increase watering frequency with drip irrigation if possible\n- Add organic mulch layers to restrict soil moisture loss\n- Maintain low crop cover or shade nets to avoid excessive evaporation",
        "recs_healthy": "- Maintain current sustainable farming practices\n- Continue routine sampling weekly to build soil acoustic trends",
        "treat_compact": "Aerate and add compost to improve texture.",
        "treat_dry": "Irrigate & mulch to lock moisture.",
        "treat_healthy": "Maintain organic cover and routine sampling.",
        
        # Navigation
        "Dashboard": "Dashboard",
        "Soil Analysis": "Soil Analysis",
        "Reports": "Reports",
        "AI Insights": "AI Insights",
        "History": "History",
        "About": "About",
        
        # Dashboard & App Header
        "TerraEcho Soil Analysis Studio": "TerraEcho Soil Analysis Studio",
        "AI Powered Soil Intelligence": "AI Powered Soil Intelligence",
        "AI Powered": "AI Powered",
        "AI-Based Soil Sound Intelligence System": "AI-Based Soil Sound Intelligence System",
        "A professional agriculture dashboard for soil sound analytics, AI-driven health scores, and smart farming guidance.": "A professional agriculture dashboard for soil sound analytics, AI-driven health scores, and smart farming guidance.",
        "Analyze Soil": "Analyze Soil",
        "Soil Waveform Preview": "Soil Waveform Preview",
        "Smart Soil": "Smart Soil",
        "Acoustic Intel": "Acoustic Intel",
        "Agri-Tech": "Agri-Tech",
        "Premium Platform": "Premium Platform",
        "Sustainable": "Sustainable",
        "Field Ready": "Field Ready",
        "Enterprise Soil Overview": "Enterprise Soil Overview",
        "Processed Samples": "Processed Samples",
        "Average Health Score": "Average Health Score",
        "Recent Soil Type": "Recent Soil Type",
        "Farming Readiness": "Farming Readiness",
        "Smart Insights": "Smart Insights",
        "Soil Acoustics Engine": "Soil Acoustics Engine",
        "Convert acoustic patterns into actionable soil health intelligence.": "Convert acoustic patterns into actionable soil health intelligence.",
        "Water Efficiency": "Water Efficiency",
        "Predict water demand and avoid waste across the farm lifecycle.": "Predict water demand and avoid waste across the farm lifecycle.",
        "Climate-Smart Actions": "Climate-Smart Actions",
        "Deliver recommendations that balance yield, sustainability, and soil longevity.": "Deliver recommendations that balance yield, sustainability, and soil longevity.",
        "Trend Monitoring": "Trend Monitoring",
        "Soil Health Trend": "Soil Health Trend",
        "Analyze your first sample to populate enterprise dashboards.": "Analyze your first sample to populate enterprise dashboards.",
        "Platform Advantages": "Platform Advantages",
        "Precision Crop Plans": "Precision Crop Plans",
        "Match crop choices to soil acoustic signatures.": "Match crop choices to soil acoustic signatures.",
        "Nutrient Forecast": "Nutrient Forecast",
        "Pinpoint soil fertility risks before planting.": "Pinpoint soil fertility risks before planting.",
        "Community Impact": "Community Impact",
        "Support climate-positive agriculture with clarity.": "Support climate-positive agriculture with clarity.",
        
        # Soil Analysis Upload Page
        "Upload soil tapping audio to analyze soil health with pro-grade AI intelligence.": "Upload soil tapping audio to analyze soil health with pro-grade AI intelligence.",
        "Upload soil tapping audio to analyze soil health": "Upload soil tapping audio to analyze soil health",
        "Drop your .wav or .mp3 sample here for instant soil type classification, moisture analysis, and AI recommendation.": "Drop your .wav or .mp3 sample here for instant soil type classification, moisture analysis, and AI recommendation.",
        "Drag & drop your audio file": "Drag & drop your audio file",
        "Accepted formats: WAV, MP3 • Less than 20MB": "Accepted formats: WAV, MP3 • Less than 20MB",
        "Premium Analysis Kit": "Premium Analysis Kit",
        "Designed for farmers, research teams, and agri-tech judges.": "Designed for farmers, research teams, and agri-tech judges.",
        "Modern soil dashboard": "Modern soil dashboard",
        "AI-driven recommendations": "AI-driven recommendations",
        "Rich visual storytelling": "Rich visual storytelling",
        "Accepted: .wav, .mp3 • Upload a sample to begin scoring.": "Accepted: .wav, .mp3 • Upload a sample to begin scoring.",
        "AI Analysis Summary": "AI Analysis Summary",
        "Uploaded Audio Details": "Uploaded Audio Details",
        "Format": "Format",
        "Size": "Size",
        "Duration": "Duration",
        "sec": "sec",
        "Acoustic classification": "Acoustic classification",
        "Soil moisture trend": "Soil moisture trend",
        "Health Score": "Health Score",
        "AI soil health rating": "AI soil health rating",
        "AI Confidence": "AI Confidence",
        "Model certainty": "Model certainty",
        "Soil Health Meter": "Soil Health Meter",
        "Soil Technical Parameters": "Soil Technical Parameters",
        "Moisture Level": "Moisture Level",
        "Compaction": "Compaction",
        "Dryness": "Dryness",
        "Acoustic Frequency": "Acoustic Frequency",
        "Signal Energy": "Signal Energy",
        "Scan Duration": "Scan Duration",
        "Soil Sound Waveform": "Soil Sound Waveform",
        "Extracted Audio Features": "Extracted Audio Features",
        "View as": "View as",
        "Bar chart": "Bar chart",
        "Line chart": "Line chart",
        "Radar chart": "Radar chart",
        "Feature Radar Summary": "Feature Radar Summary",
        "Feature Trend Summary": "Feature Trend Summary",
        "Value": "Value",
        "Feature Values": "Feature Values",
        "Current vs Ideal Parameters": "Current vs Ideal Parameters",
        "Parameter": "Parameter",
        "Online": "Online",
        "Ask TerraEcho AI": "Ask TerraEcho AI",
        "Chat with our AI agronomist assistant about soil aeration, crop cycles, or irrigation.": "Chat with our AI agronomist assistant about soil aeration, crop cycles, or irrigation.",
        "My soil is compact. What should I do?": "My soil is compact. What should I do?",
        "Ask TerraEcho": "Ask TerraEcho",
        "TerraEcho Agronomist": "TerraEcho Agronomist",
        "Download Soil Report PDF": "Download Soil Report PDF",
        
        # Reports
        "Reports & Exports": "Reports & Exports",
        "Download investor-grade soil health reports and export your portfolio.": "Download investor-grade soil health reports and export your portfolio.",
        "Total Reports": "Total Reports",
        "Recent Run": "Recent Run",
        "Export Entire Portfolio": "Export Entire Portfolio",
        "Download all generated soil reports in a single zip archive.": "Download all generated soil reports in a single zip archive.",
        "Prepare Report Bundle": "Prepare Report Bundle",
        "Download TerraEcho Report Bundle": "Download TerraEcho Report Bundle",
        "Available Soil Reports": "Available Soil Reports",
        "Sample Metadata": "Sample Metadata",
        "Sample": "Sample",
        "Unknown Location": "Unknown Location",
        "Analysis Result": "Analysis Result",
        "Download PDF": "Download PDF",
        
        # AI Insights
        "AI Agronomy Insights": "AI Agronomy Insights",
        "Deep soil acoustic intelligence for smarter agronomy and ecological health monitoring.": "Deep soil acoustic intelligence for smarter agronomy and ecological health monitoring.",
        "Frequency Intelligence": "Frequency Intelligence",
        "Understand how sound spectral patterns map to soil moisture and compaction level variations.": "Understand how sound spectral patterns map to soil moisture and compaction level variations.",
        "Crop Reflection": "Crop Reflection",
        "Match agro-recommendations to the detected soil health profile for maximum crop yield potential.": "Match agro-recommendations to the detected soil health profile for maximum crop yield potential.",
        "Sustainability Index": "Sustainability Index",
        "Track regenerative farming signals through acoustic soil analysis and organic matter trends.": "Track regenerative farming signals through acoustic soil analysis and organic matter trends.",
        "Health Score Distribution": "Health Score Distribution",
        "Historical Analysis Health Scores": "Historical Analysis Health Scores",
        "Collect soil samples to activate AI insight dashboards.": "Collect soil samples to activate AI insight dashboards.",
        
        # History
        "Soil History": "Soil History",
        "Review and compare past soil analyses performed in your workspace.": "Review and compare past soil analyses performed in your workspace.",
        "Analysis Log": "Analysis Log",
        "Notes": "Notes",
        
        # About
        "About TerraEcho": "About TerraEcho",
        "Built for farmers, researchers, NGOs, and agri-tech innovators focused on resilient soil systems.": "Built for farmers, researchers, NGOs, and agri-tech innovators focused on resilient soil systems.",
        "Mission": "Mission",
        "Empower sustainable agriculture with accurate, easy-to-use soil health intelligence using acoustic resonance.": "Empower sustainable agriculture with accurate, easy-to-use soil health intelligence using acoustic resonance.",
        "Vision": "Vision",
        "Transform soil scanning into fast, confident decisions for every field to enhance global crop security.": "Transform soil scanning into fast, confident decisions for every field to enhance global crop security.",
        "Values": "Values",
        "Precision, environmental sustainability, technological accessibility, and measurable climate impact.": "Precision, environmental sustainability, technological accessibility, and measurable climate impact.",
        "Get in Touch": "Get in Touch",
        "Contact": "Contact",
        "Open Source": "Open Source",
        "GitHub Repository": "GitHub Repository",
        "Eco Impact": "Eco Impact",
        "Sustainability": "Sustainability",
        "Supporting soil resilience, carbon sequestration, and climate-smart food networks.": "Supporting soil resilience, carbon sequestration, and climate-smart food networks."
    },
    "Kannada": {
        "Soil Type": "ಮಣ್ಣಿನ ಪ್ರಕಾರ",
        "Moisture": "ತೇವಾಂಶ",
        "Confidence": "ವಿಶ್ವಾಸ",
        "Duration": "ಅವಧಿ",
        "Recommendation": "ಶಿಫಾರಸು",
        "Soil Metrics": "ಮಣ್ಣಿನ ಮೆಟ್ರಿಕ್ಸ್",
        "Feature Graphs": "ವೈಶಿಷ್ಟ್ಯ ಗ್ರಾಫ್‌ಗಳು",
        "AI Recommendations": "AI ಶಿಫಾರಸುಗಳು",
        
        "Compact Soil": "ಗಟ್ಟಿ ಮಣ್ಣು",
        "Dry Soil": "ಒಣ ಮಣ್ಣು",
        "Healthy Soil": "ಆರೋಗ್ಯಕರ ಮಣ್ಣು",
        "High": "ಹೆಚ್ಚು",
        "Moderate": "ಮಧ್ಯಮ",
        "Low": "ಕಡಿಮೆ",
        "Optimal": "ಸೂಕ್ತ",
        
        "⚠ Soil Aeration Recommended": "⚠ ಮಣ್ಣಿನ ಗಾಳಿಯಾಟ ಶಿಫಾರಸು",
        "💧 Soil Irrigation Needed": "💧 ಮಣ್ಣಿನ ನೀರಾವರಿ ಅಗತ್ಯ",
        "✅ Soil Condition Stable & Good": "✅ ಮಣ್ಣಿನ ಸ್ಥಿತಿ ಸ್ಥಿರ ಮತ್ತು ಉತ್ತಮ",
        
        "recs_compact": "- ಸಡಿಲ ವಿನ್ಯಾಸಕ್ಕೆ ಸಾವಯವ ಗೊಬ್ಬರ ಸೇರಿಸಿ ಮತ್ತು ಜೈವಿಕ ಪದಾರ್ಥ ಪರಿಚಯಿಸಿ\n- ನೀರು ನಿಲ್ಲುವುದನ್ನು ತಡೆಯಲು ಕ್ಷೇತ್ರ ನಿಕಾಸಿ ಸುಧಾರಿಸಿ\n- ಹೆಚ್ಚಿನ ತೇವಾಂಶದ ದಿನಗಳಲ್ಲಿ ಭಾರೀ ಯಂತ್ರ ಬಳಕೆ ತಪ್ಪಿಸಿ\n- 3 ದಿನಗಳ ನಂತರ ಮಣ್ಣಿನ ತೇವಾಂಶ ಮರು-ಪರಿಶೀಲಿಸಿ",
        "recs_dry": "- ಸಾಧ್ಯವಾದರೆ ಹನಿ ನೀರಾವರಿ ಬಳಸಿ ನೀರು ಹಾಕುವ ಆವರ್ತನ ಹೆಚ್ಚಿಸಿ\n- ತೇವಾಂಶ ಉಳಿಸಲು ಸಾವಯವ ಹೊದಿಕೆ ಪದರ ಸೇರಿಸಿ\n- ಅತಿಯಾದ ಆವಿಯಾಗುವಿಕೆ ತಪ್ಪಿಸಲು ನೆರಳು ನಿರ್ವಹಿಸಿ",
        "recs_healthy": "- ಪ್ರಸ್ತುತ ಸಮರ್ಥನೀಯ ಕೃಷಿ ಅಭ್ಯಾಸಗಳನ್ನು ಮುಂದುವರಿಸಿ\n- ನಿಯಮಿತವಾಗಿ ಮಣ್ಣಿನ ಪರೀಕ್ಷೆ ಮುಂದುವರಿಸಿ",
        "treat_compact": "ಮಣ್ಣನ್ನು ಸಡಿಲಗೊಳಿಸಿ ಮತ್ತು ಗೊಬ್ಬರ ಸೇರಿಸಿ.",
        "treat_dry": "ತೇವಾಂಶ ಉಳಿಸಲು ನೀರಾವರಿ ಮತ್ತು ಹೊದಿಕೆ ಬಳಸಿ.",
        "treat_healthy": "ಪ್ರಸ್ತುತ ಸಮರ್ಥನೀಯ ಅಭ್ಯಾಸಗಳನ್ನು ನಿರ್ವಹಿಸಿ.",
        
        # Navigation
        "Dashboard": "ನಿಯಂತ್ರಣ ಫಲಕ",
        "Soil Analysis": "ಮಣ್ಣಿನ ವಿಶ್ಲೇಷಣೆ",
        "Reports": "ವರದಿಗಳು",
        "AI Insights": "AI ಒಳನೋಟಗಳು",
        "History": "ಇತಿಹಾಸ",
        "About": "ಬಗ್ಗೆ",
        
        # Dashboard & App Header
        "TerraEcho Soil Analysis Studio": "ಟೆರ್ರಾಎಕೋ ಮಣ್ಣಿನ ವಿಶ್ಲೇಷಣಾ ಸ್ಟುಡಿಯೋ",
        "AI Powered Soil Intelligence": "AI ಚಾಲಿತ ಮಣ್ಣಿನ ಬುದ್ಧಿಮತ್ತೆ",
        "AI Powered": "AI ಚಾಲಿತ",
        "AI-Based Soil Sound Intelligence System": "AI-ಆಧಾರಿತ ಮಣ್ಣಿನ ಧ್ವನಿ ಬುದ್ಧಿಮತ್ತೆ ವ್ಯವಸ್ಥೆ",
        "A professional agriculture dashboard for soil sound analytics, AI-driven health scores, and smart farming guidance.": "ಮಣ್ಣಿನ ಧ್ವನಿ ವಿಶ್ಲೇಷಣೆ, AI-ಚಾಲಿತ ಆರೋಗ್ಯ ಅಂಕಗಳು ಮತ್ತು ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ಮಾರ್ಗದರ್ಶನಕ್ಕಾಗಿ ವೃತ್ತಿಪರ ಕೃಷಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್.",
        "Analyze Soil": "ಮಣ್ಣು ವಿಶ್ಲೇಷಿಸಿ",
        "Soil Waveform Preview": "ಮಣ್ಣಿನ ತರಂಗ ರೂಪದ ಮುನ್ನೋಟ",
        "Smart Soil": "ಸ್ಮಾರ್ಟ್ ಮಣ್ಣು",
        "Acoustic Intel": "ಅಕೌಸ್ಟಿಕ್ ಇಂಟೆಲ್",
        "Agri-Tech": "ಅಗ್ರಿ-ಟೆಕ್",
        "Premium Platform": "ಪ್ರೀಮಿಯಂ ವೇದಿಕೆ",
        "Sustainable": "ಸಮರ್ಥನೀಯ",
        "Field Ready": "ಕ್ಷೇತ್ರ ಸಿದ್ಧ",
        "Enterprise Soil Overview": "ಉದ್ಯಮ ಮಣ್ಣಿನ ಅವಲೋಕನ",
        "Processed Samples": "ಸಂಸ್ಕರಿಸಿದ ಮಾದರಿಗಳು",
        "Average Health Score": "ಸರಾಸರಿ ಆರೋಗ್ಯ ಸ್ಕೋರ್",
        "Recent Soil Type": "ಇತ್ತೀಚಿನ ಮಣ್ಣಿನ ಪ್ರಕಾರ",
        "Farming Readiness": "ಕೃಷಿ ಸಿದ್ಧತೆ",
        "Smart Insights": "ಸ್ಮಾರ್ಟ್ ಒಳನೋಟಗಳು",
        "Soil Acoustics Engine": "ಮಣ್ಣಿನ ಅಕೌಸ್ಟಿಕ್ಸ್ ಎಂಜಿನ್",
        "Convert acoustic patterns into actionable soil health intelligence.": "ಅಕೌಸ್ಟಿಕ್ ಮಾದರಿಗಳನ್ನು ಕ್ರಿಯಾಶೀಲ ಮಣ್ಣಿನ ಆರೋಗ್ಯ ಬುದ್ಧಿಮತ್ತೆಯಾಗಿ ಪರಿವರ್ತಿಸಿ.",
        "Water Efficiency": "ನೀರಿನ ದಕ್ಷತೆ",
        "Predict water demand and avoid waste across the farm lifecycle.": "ಕೃಷಿ ಜೀವನಚಕ್ರದಾದ್ಯಂತ ನೀರಿನ ಬೇಡಿಕೆಯನ್ನು ಊಹಿಸಿ ಮತ್ತು ವ್ಯರ್ಥವನ್ನು ತಡೆಯಿರಿ.",
        "Climate-Smart Actions": "ಹವಾಮಾನ-ಸ್ಮಾರ್ಟ್ ಕ್ರಮಗಳು",
        "Deliver recommendations that balance yield, sustainability, and soil longevity.": "ಇಳುವರಿ, ಸಮರ್ಥನೀಯತೆ ಮತ್ತು ಮಣ್ಣಿನ ದೀರ್ಘಾಯುಷ್ಯವನ್ನು ಸಮತೋಲನಗೊಳಿಸುವ ಶಿಫಾರಸುಗಳನ್ನು ಒದಗಿಸಿ.",
        "Trend Monitoring": "ಪ್ರವೃತ್ತಿ ಮಾನಿಟರಿಂಗ್",
        "Soil Health Trend": "ಮಣ್ಣಿನ ಆರೋಗ್ಯ ಪ್ರವೃತ್ತಿ",
        "Analyze your first sample to populate enterprise dashboards.": "ಉದ್ಯಮ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗಳನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಲು ನಿಮ್ಮ ಮೊದಲ ಮಾದರಿಯನ್ನು ವಿಶ್ಲೇಷಿಸಿ.",
        "Platform Advantages": "ವೇದಿಕೆಯ ಪ್ರಯೋಜನಗಳು",
        "Precision Crop Plans": "ನಿಖರ ಬೆಳೆ ಯೋಜನೆಗಳು",
        "Match crop choices to soil acoustic signatures.": "ಮಣ್ಣಿನ ಅಕೌಸ್ಟಿಕ್ ಸಿಗ್ನೇಚರ್‌ಗಳಿಗೆ ಬೆಳೆ ಆಯ್ಕೆಗಳನ್ನು ಹೊಂದಿಸಿ.",
        "Nutrient Forecast": "ಪೋಷಕಾಂಶಗಳ ಮುನ್ಸೂಚನೆ",
        "Pinpoint soil fertility risks before planting.": "ನಾಟಿ ಮಾಡುವ ಮೊದಲು ಮಣ್ಣಿನ ಫಲವತ್ತತೆಯ ಅಪಾಯಗಳನ್ನು ಗುರುತಿಸಿ.",
        "Community Impact": "ಸಮುದಾಯದ ಪ್ರಭಾವ",
        "Support climate-positive agriculture with clarity.": "ಸ್ಪಷ್ಟತೆಯೊಂದಿಗೆ ಹವಾಮಾನ-ಧನಾತ್ಮಕ ಕೃಷಿಯನ್ನು ಬೆಂಬಲಿಸಿ.",
        
        # Soil Analysis Upload Page
        "Upload soil tapping audio to analyze soil health with pro-grade AI intelligence.": "ವೃತ್ತಿಪರ ದರ್ಜೆಯ AI ಬುದ್ಧಿಮತ್ತೆಯೊಂದಿಗೆ ಮಣ್ಣಿನ ಆರೋಗ್ಯವನ್ನು ವಿಶ್ಲೇಷಿಸಲು ಧ್ವನಿಯನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
        "Upload soil tapping audio to analyze soil health": "ಮಣ್ಣಿನ ಆರೋಗ್ಯವನ್ನು ವಿಶ್ಲೇಷಿಸಲು ಧ್ವನಿ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
        "Drop your .wav or .mp3 sample here for instant soil type classification, moisture analysis, and AI recommendation.": "ತ್ವರಿತ ಮಣ್ಣಿನ ಪ್ರಕಾರ ವರ್ಗೀಕರಣ, ತೇವಾಂಶ ವಿಶ್ಲೇಷಣೆ ಮತ್ತು AI ಶಿಫಾರಸುಗಳಿಗಾಗಿ ನಿಮ್ಮ .wav ಅಥವಾ .mp3 ಮಾದರಿಯನ್ನು ಇಲ್ಲಿ ಹಾಕಿ.",
        "Drag & drop your audio file": "ನಿಮ್ಮ ಆಡಿಯೊ ಫೈಲ್ ಅನ್ನು ಇಲ್ಲಿ ಎಳೆಯಿರಿ ಮತ್ತು ಬಿಡಿ",
        "Accepted formats: WAV, MP3 • Less than 20MB": "ಸ್ವೀಕೃತ ಫಾರ್ಮ್ಯಾಟ್‌ಗಳು: WAV, MP3 • 20MB ಗಿಂತ ಕಡಿಮೆ",
        "Premium Analysis Kit": "ಪ್ರೀಮಿಯಂ ವಿಶ್ಲೇಷಣಾ ಕಿಟ್",
        "Designed for farmers, research teams, and agri-tech judges.": "ರೈತರು, ಸಂಶೋಧನಾ ತಂಡಗಳು ಮತ್ತು ಅಗ್ರಿ-ಟೆಕ್ ತೀರ್ಪುಗಾರರಿಗಾಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಲಾಗಿದೆ.",
        "Modern soil dashboard": "ಆಧುನಿಕ ಮಣ್ಣಿನ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        "AI-driven recommendations": "AI-ಚಾಲಿತ ಶಿಫಾರಸುಗಳು",
        "Rich visual storytelling": "ಶ್ರೀಮಂತ ದೃಶ್ಯ ಕಥೆ ಹೇಳುವಿಕೆ",
        "Accepted: .wav, .mp3 • Upload a sample to begin scoring.": "ಸ್ವೀಕರಿಸಲಾಗಿದೆ: .wav, .mp3 • ಸ್ಕೋರಿಂಗ್ ಪ್ರಾರಂಭಿಸಲು ಮಾದರಿಯನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
        "AI Analysis Summary": "AI ವಿಶ್ಲೇಷಣೆ ಸಾರಾಂಶ",
        "Uploaded Audio Details": "ಅಪ್‌ಲೋಡ್ ಮಾಡಿದ ಆಡಿಯೊ ವಿವರಗಳು",
        "Format": "ಫಾರ್ಮ್ಯಾಟ್",
        "Size": "ಗಾತ್ರ",
        "Duration": "ಅವಧಿ",
        "sec": "ಸೆಕೆಂಡು",
        "Acoustic classification": "ಅಕೌಸ್ಟಿಕ್ ವರ್ಗೀಕರಣ",
        "Soil moisture trend": "ಮಣ್ಣಿನ ತೇವಾಂಶದ ಪ್ರವೃತ್ತಿ",
        "Health Score": "ಆರೋಗ್ಯ ಸ್ಕೋರ್",
        "AI soil health rating": "AI ಮಣ್ಣಿನ ಆರೋಗ್ಯ ರೇಟಿಂಗ್",
        "AI Confidence": "AI ವಿಶ್ವಾಸಾರ್ಹತೆ",
        "Model certainty": "ಮಾದರಿ ನಿಶ್ಚಿತತೆ",
        "Soil Health Meter": "ಮಣ್ಣಿನ ಆರೋಗ್ಯ ಮೀಟರ್",
        "Soil Technical Parameters": "ಮಣ್ಣಿನ ತಾಂತ್ರಿಕ ನಿಯತಾಂಕಗಳು",
        "Moisture Level": "ತೇವಾಂಶದ ಮಟ್ಟ",
        "Compaction": "ಮಣ್ಣಿನ ಗಟ್ಟಿತನ",
        "Dryness": "ಒಣಗುವಿಕೆ",
        "Acoustic Frequency": "ಅಕೌಸ್ಟಿಕ್ ಆವರ್ತನ",
        "Signal Energy": "ಸಿಗ್ನಲ್ ಶಕ್ತಿ",
        "Scan Duration": "ಸ್ಕ್ಯಾನ್ ಅವಧಿ",
        "Soil Sound Waveform": "ಮಣ್ಣಿನ ಧ್ವನಿ ತರಂಗರೂಪ",
        "Extracted Audio Features": "ತೆಗೆದ ಆಡಿಯೊ ವೈಶಿಷ್ಟ್ಯಗಳು",
        "View as": "ಹೀಗೆ ವೀಕ್ಷಿಸಿ",
        "Bar chart": "ಬಾರ್ ಚಾರ್ಟ್",
        "Line chart": "ಲೈನ್ ಚಾರ್ಟ್",
        "Radar chart": "ರಾಡಾರ್ ಚಾರ್ಟ್",
        "Feature Radar Summary": "ವೈಶಿಷ್ಟ್ಯ ರಾಡಾರ್ ಸಾರಾಂಶ",
        "Feature Trend Summary": "ವೈಶಿಷ್ಟ್ಯ ಪ್ರವೃತ್ತಿ ಸಾರಾಂಶ",
        "Value": "ಮೌಲ್ಯ",
        "Feature Values": "ವೈಶಿಷ್ಟ್ಯ ಮೌಲ್ಯಗಳು",
        "Current vs Ideal Parameters": "ಪ್ರಸ್ತುತ ವಿರುದ್ಧ ಆದರ್ಶ ನಿಯತಾಂಕಗಳು",
        "Parameter": "ನಿಯತಾಂಕ",
        "Online": "ಆನ್‌ಲೈನ್",
        "Ask TerraEcho AI": "ಟೆರ್ರಾಎಕೋ AI ಅನ್ನು ಕೇಳಿ",
        "Chat with our AI agronomist assistant about soil aeration, crop cycles, or irrigation.": "ಮಣ್ಣಿನ ಗಾಳಿಯಾಡುವಿಕೆ, ಬೆಳೆ ಚಕ್ರಗಳು ಅಥವಾ ನೀರಾವರಿ ಬಗ್ಗೆ ನಮ್ಮ AI ಕೃಷಿ ವಿಜ್ಞಾನಿ ಸಹಾಯಕರೊಂದಿಗೆ ಚಾಟ್ ಮಾಡಿ.",
        "My soil is compact. What should I do?": "ನನ್ನ ಮಣ್ಣು ಗಟ್ಟಿಯಾಗಿದೆ. ನಾನು ಏನು ಮಾಡಬೇಕು?",
        "Ask TerraEcho": "ಟೆರ್ರಾಎಕೋ ಕೇಳಿ",
        "TerraEcho Agronomist": "ಟೆರ್ರಾಎಕೋ ಕೃಷಿ ವಿಜ್ಞಾನಿ",
        "Download Soil Report PDF": "ಮಣ್ಣಿನ ವರದಿ PDF ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
        
        # Reports
        "Reports & Exports": "ವರದಿಗಳು ಮತ್ತು ರಫ್ತುಗಳು",
        "Download investor-grade soil health reports and export your portfolio.": "ಹೂಡಿಕೆದಾರರ ದರ್ಜೆಯ ಮಣ್ಣಿನ ಆರೋಗ್ಯ ವರದಿಗಳನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ ಮತ್ತು ನಿಮ್ಮ ಪೋರ್ಟ್‌ಫೋಲಿಯೊವನ್ನು ರಫ್ತು ಮಾಡಿ.",
        "Total Reports": "ಒಟ್ಟು ವರದಿಗಳು",
        "Recent Run": "ಇತ್ತೀಚಿನ ರನ್",
        "Export Entire Portfolio": "ಇಡೀ ಪೋರ್ಟ್‌ಫೋಲಿಯೊ ರಫ್ತು ಮಾಡಿ",
        "Download all generated soil reports in a single zip archive.": "ರಚಿಸಲಾದ ಎಲ್ಲಾ ಮಣ್ಣಿನ ವರದಿಗಳನ್ನು ಒಂದೇ ಜಿಪ್ ಆರ್ಕೈವ್‌ನಲ್ಲಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ.",
        "Prepare Report Bundle": "ವರದಿ ಬಂಡಲ್ ತಯಾರಿಸಿ",
        "Download TerraEcho Report Bundle": "ವರದಿ ಬಂಡಲ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
        "Available Soil Reports": "ಲಭ್ಯವಿರುವ ಮಣ್ಣಿನ ವರದಿಗಳು",
        "Sample Metadata": "ಮಾದರಿ ಮೆಟಾಡೇಟಾ",
        "Sample": "ಮಾದರಿ",
        "Unknown Location": "ಅಜ್ಞಾತ ಸ್ಥಳ",
        "Analysis Result": "ವಿಶ್ಲೇಷಣೆಯ ಫಲಿತಾಂಶ",
        "Download PDF": "PDF ಡೌನ್‌ಲೋಡ್",
        
        # AI Insights
        "AI Agronomy Insights": "AI ಕೃಷಿ ಒಳನೋಟಗಳು",
        "Deep soil acoustic intelligence for smarter agronomy and ecological health monitoring.": "ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ಮತ್ತು ಪರಿಸರ ಆರೋಗ್ಯ ಮೇಲ್ವಿಚಾರಣೆಗಾಗಿ ಆಳವಾದ ಮಣ್ಣಿನ ಅಕೌಸ್ಟಿಕ್ ಬುದ್ಧಿಮತ್ತೆ.",
        "Frequency Intelligence": "ಆವರ್ತನ ಬುದ್ಧಿಮತ್ತೆ",
        "Understand how sound spectral patterns map to soil moisture and compaction level variations.": "ಧ್ವನಿ ಸ್ಪೆಕ್ಟ್ರಲ್ ಮಾದರಿಗಳು ಮಣ್ಣಿನ ತೇವಾಂಶ ಮತ್ತು ಗಟ್ಟಿತನದ ಮಟ್ಟಗಳ ವ್ಯತ್ಯಾಸಗಳಿಗೆ ಹೇಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತವೆ ಎಂಬುದನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.",
        "Crop Reflection": "ಬೆಳೆ ಪ್ರತಿಫಲನ",
        "Match agro-recommendations to the detected soil health profile for maximum crop yield potential.": "ಗರಿಷ್ಠ ಬೆಳೆ ಇಳುವರಿ ಸಾಮರ್ಥ್ಯಕ್ಕಾಗಿ ಪತ್ತೆಯಾದ ಮಣ್ಣಿನ ಆರೋಗ್ಯ ಪ್ರೊಫೈಲ್‌ಗೆ ಕೃಷಿ ಶಿಫಾರಸುಗಳನ್ನು ಹೊಂದಿಸಿ.",
        "Sustainability Index": "ಸಮರ್ಥನೀಯತೆ ಸೂಚ್ಯಂಕ",
        "Track regenerative farming signals through acoustic soil analysis and organic matter trends.": "ಅಕೌಸ್ಟಿಕ್ ಮಣ್ಣಿನ ವಿಶ್ಲೇಷಣೆ ಮತ್ತು ಸಾವಯವ ಪದಾರ್ಥಗಳ ಪ್ರವೃತ್ತಿಗಳ ಮೂಲಕ ಪುನರುತ್ಪಾದಕ ಕೃಷಿ ಸಂಕೇತಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.",
        "Health Score Distribution": "ಆರೋಗ್ಯ ಸ್ಕೋರ್ ವಿತರಣೆ",
        "Historical Analysis Health Scores": "ಐತಿಹಾಸಿಕ ವಿಶ್ಲೇಷಣೆ ಆರೋಗ್ಯ ಅಂಕಗಳು",
        "Collect soil samples to activate AI insight dashboards.": "AI ಒಳನೋಟ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗಳನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಲು ಮಣ್ಣಿನ ಮಾದರಿಗಳನ್ನು ಸಂಗ್ರಹಿಸಿ.",
        
        # History
        "Soil History": "ಮಣ್ಣಿನ ಇತಿಹಾಸ",
        "Review and compare past soil analyses performed in your workspace.": "ನಿಮ್ಮ ಕಾರ್ಯಕ್ಷೇತ್ರದಲ್ಲಿ ನಿರ್ವಹಿಸಲಾದ ಹಿಂದಿನ ಮಣ್ಣಿನ ವಿಶ್ಲೇಷಣೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಹೋಲಿಕೆ ಮಾಡಿ.",
        "Analysis Log": "ವಿಶ್ಲೇಷಣೆ ಲಾಗ್",
        "Notes": "ಟಿಪ್ಪಣಿಗಳು",
        
        # About
        "About TerraEcho": "ಟೆರ್ರಾಎಕೋ ಬಗ್ಗೆ",
        "Built for farmers, researchers, NGOs, and agri-tech innovators focused on resilient soil systems.": "ಸ್ಥಿತಿಸ್ಥಾಪಕ ಮಣ್ಣಿನ ವ್ಯವಸ್ಥೆಗಳ ಮೇಲೆ ಕೇಂದ್ರೀಕರಿಸಿದ ರೈತರು, ಸಂಶೋಧಕರು, ಎನ್‌ಜಿಒಗಳು ಮತ್ತು ಅಗ್ರಿ-ಟೆಕ್ ನಾವೀನ್ಯಕಾರರಿಗಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ.",
        "Mission": "ಧ್ಯೇಯ",
        "Empower sustainable agriculture with accurate, easy-to-use soil health intelligence using acoustic resonance.": "ಅಕೌಸ್ಟಿಕ್ ರೆಸೋನೆನ್ಸ್ ಬಳಸಿ ನಿಖರವಾದ, ಬಳಸಲು ಸುಲಭವಾದ ಮಣ್ಣಿನ ಆರೋಗ್ಯ ಬುದ್ಧಿಮತ್ತೆಯೊಂದಿಗೆ ಸಮರ್ಥನೀಯ ಕೃಷಿಯನ್ನು ಸಬಲೀಕರಣಗೊಳಿಸಿ.",
        "Vision": "ದೂರದೃಷ್ಟಿ",
        "Transform soil scanning into fast, confident decisions for every field to enhance global crop security.": "ಜಾಗತಿಕ ಬೆಳೆ ಸುರಕ್ಷತೆಯನ್ನು ಹೆಚ್ಚಿಸಲು ಪ್ರತಿ ಕ್ಷೇತ್ರಕ್ಕೂ ವೇಗವಾದ, ವಿಶ್ವಾಸಾರ್ಹ ನಿರ್ಧಾರಗಳಾಗಿ ಮಣ್ಣಿನ ಸ್ಕ್ಯಾನಿಂಗ್ ಅನ್ನು ಪರಿವರ್ತಿಸಿ.",
        "Values": "ಮೌಲ್ಯಗಳು",
        "Precision, environmental sustainability, technological accessibility, and measurable climate impact.": "ನಿಖರತೆ, ಪರಿಸರ ಸಮರ್ಥನೀಯತೆ, ತಾಂತ್ರಿಕ ಪ್ರವೇಶ ಮತ್ತು ಅಳೆಯಬಹುದಾದ ಹವಾಮಾನ ಪ್ರಭಾವ.",
        "Get in Touch": "ಸಂಪರ್ಕಿಸಿ",
        "Contact": "ಸಂಪರ್ಕ",
        "Open Source": "ಮುಕ್ತ ಆಕರ",
        "GitHub Repository": "ಗಿಟ್‌ಹಬ್ ರೆಪೊಸಿಟರಿ",
        "Eco Impact": "ಪರಿಸರ ಪ್ರಭಾವ",
        "Sustainability": "ಸಮರ್ಥನೀಯತೆ",
        "Supporting soil resilience, carbon sequestration, and climate-smart food networks.": "ಮಣ್ಣಿನ ಸ್ಥಿತಿಸ್ಥಾಪಕತ್ವ, ಕಾರ್ಬನ್ ಸೀಕ್ವೆಸ್ಟ್ರೇಶನ್ ಮತ್ತು ಹವಾಮಾನ-ಸ್ಮಾರ್ಟ್ ಆಹಾರ ಜಾಲಗಳನ್ನು ಬೆಂಬಲಿಸುವುದು."
    },
    "Hindi": {
        "Soil Type": "मिट्टी का प्रकार",
        "Moisture": "नमी",
        "Confidence": "आत्मविश्वास",
        "Duration": "अवधि",
        "Recommendation": "सिफारिश",
        "Soil Metrics": "मिट्टी के मेट्रिक्स",
        "Feature Graphs": "फ़ीचर ग्राफ़",
        "AI Recommendations": "AI सिफारिशें",
        
        "Compact Soil": "कठोर मिट्टी",
        "Dry Soil": "सूखी मिट्टी",
        "Healthy Soil": "स्वस्थ मिट्टी",
        "High": "अधिक",
        "Moderate": "मध्यम",
        "Low": "कम",
        "Optimal": "इष्टतम",
        
        "⚠ Soil Aeration Recommended": "⚠ मिट्टी के वातन की सिफारिश",
        "💧 Soil Irrigation Needed": "💧 सिंचाई की आवश्यकता",
        "✅ Soil Condition Stable & Good": "✅ मिट्टी की स्थिति स्थिर और अच्छी",
        
        "recs_compact": "- मिट्टी को ढीला करने के लिए जैविक खाद डालें\n- जलभराव को रोकने के लिए जल निकासी में सुधार करें\n- नमी वाले दिनों में भारी मशीनरी के उपयोग से बचें\n- 3 दिन बाद फिर से परीक्षण करें",
        "recs_dry": "- ड्रिप सिंचाई के साथ सिंचाई की आवृत्ति बढ़ाएं\n- नमी के नुकसान को रोकने के लिए मल्च परतें जोड़ें\n- वाष्पीकरण से बचने के लिए छाया बनाए रखें",
        "recs_healthy": "- वर्तमान टिकाऊ कृषि प्रथाओं को बनाए रखें\n- नियमित रूप से परीक्षण जारी रखें",
        "treat_compact": "मिट्टी को ढीला करें और खाद डालें।",
        "treat_dry": "नमी बनाए रखने के लिए सिंचाई करें।",
        "treat_healthy": "टिकाऊ प्रथाओं को बनाए रखें।",
        
        # Navigation
        "Dashboard": "डैशबोर्ड",
        "Soil Analysis": "मिट्टी विश्लेषण",
        "Reports": "रिपोर्ट्स",
        "AI Insights": "AI अंतर्दृष्टि",
        "History": "इतिहास",
        "About": "विवरण",
        
        # Dashboard & App Header
        "TerraEcho Soil Analysis Studio": "टेराइको सॉइल एनालिसिस स्टूडियो",
        "AI Powered Soil Intelligence": "AI संचालित मिट्टी की समझ",
        "AI Powered": "AI संचालित",
        "AI-Based Soil Sound Intelligence System": "AI-आधारित मृदा ध्वनि बुद्धिमत्ता प्रणाली",
        "A professional agriculture dashboard for soil sound analytics, AI-driven health scores, and smart farming guidance.": "मिट्टी ध्वनि विश्लेषण, AI-संचालित स्वास्थ्य स्कोर और स्मार्ट खेती मार्गदर्शन के लिए एक पेशेवर कृषि डैशबोर्ड।",
        "Analyze Soil": "मिट्टी का विश्लेषण",
        "Soil Waveform Preview": "मृदा तरंग रूप पूर्वावलोकन",
        "Smart Soil": "स्मार्ट मिट्टी",
        "Acoustic Intel": "ध्वनिक इंटेलिजेंस",
        "Agri-Tech": "एग्री-टेक",
        "Premium Platform": "प्रीमियम प्लेटफॉर्म",
        "Sustainable": "सतत विकास",
        "Field Ready": "खेत के लिए तैयार",
        "Enterprise Soil Overview": "उद्यम मृदा अवलोकन",
        "Processed Samples": "प्रसंस्कृत नमूने",
        "Average Health Score": "औसत स्वास्थ्य स्कोर",
        "Recent Soil Type": "हालिया मिट्टी का प्रकार",
        "Farming Readiness": "कृषि तत्परता",
        "Smart Insights": "स्मार्ट अंतर्दृष्टि",
        "Soil Acoustics Engine": "सॉइल एकोस्टिक्स इंजन",
        "Convert acoustic patterns into actionable soil health intelligence.": "ध्वनिक पैटर्न को व्यावहारिक मृदा स्वास्थ्य समझ में परिवर्तित करें।",
        "Water Efficiency": "जल दक्षता",
        "Predict water demand and avoid waste across the farm lifecycle.": "कृषि जीवनचक्र में पानी की मांग का अनुमान लगाएं और बर्बादी रोकें।",
        "Climate-Smart Actions": "जलवायु-स्मार्ट कदम",
        "Deliver recommendations that balance yield, sustainability, and soil longevity.": "ऐसी सिफारिशें प्रदान करें जो उपज, स्थिरता और मिट्टी की दीर्घायु को संतुलित करती हैं।",
        "Trend Monitoring": "प्रवृत्ति निगरानी",
        "Soil Health Trend": "मृदा स्वास्थ्य प्रवृत्ति",
        "Analyze your first sample to populate enterprise dashboards.": "उद्यम डैशबोर्ड को सक्रिय करने के लिए अपना पहला नमूना विश्लेषणात्मक करें।",
        "Platform Advantages": "मंच के लाभ",
        "Precision Crop Plans": "सटीक फसल योजनाएं",
        "Match crop choices to soil acoustic signatures.": "मिट्टी के ध्वनिक हस्ताक्षरों के साथ फसल विकल्पों का मिलान करें।",
        "Nutrient Forecast": "पोषक तत्व पूर्वानुमान",
        "Pinpoint soil fertility risks before planting.": "रोपण से पहले मिट्टी की उर्वरता के जोखिमों की पहचान करें।",
        "Community Impact": "सामुदायिक प्रभाव",
        "Support climate-positive agriculture with clarity.": "स्पष्टता के साथ जलवायु-सकारात्मक कृषि का समर्थन करें।",
        
        # Soil Analysis Upload Page
        "Upload soil tapping audio to analyze soil health with pro-grade AI intelligence.": "पेशेवर दर्जे की AI बुद्धिमत्ता के साथ मिट्टी के स्वास्थ्य का विश्लेषण करने के लिए ध्वनि अपलोड करें।",
        "Upload soil tapping audio to analyze soil health": "मिट्टी के स्वास्थ्य का विश्लेषण करने के लिए ध्वनि अपलोड करें",
        "Drop your .wav or .mp3 sample here for instant soil type classification, moisture analysis, and AI recommendation.": "तत्काल मिट्टी प्रकार वर्गीकरण, नमी विश्लेषण और AI सिफारिश के लिए अपना .wav या .mp3 नमूना यहां डालें।",
        "Drag & drop your audio file": "अपनी ऑडियो फ़ाइल खींचें और यहाँ छोड़ें",
        "Accepted formats: WAV, MP3 • Less than 20MB": "स्वीकृत प्रारूप: WAV, MP3 • 20MB से कम",
        "Premium Analysis Kit": "प्रीमियम विश्लेषण किट",
        "Designed for farmers, research teams, and agri-tech judges.": "किसानों, अनुसंधान टीमों और एग्री-टेक जजों के लिए डिज़ाइन किया गया।",
        "Modern soil dashboard": "आधुनिक मृदा डैशबोर्ड",
        "AI-driven recommendations": "AI-संचालित सिफारिशें",
        "Rich visual storytelling": "समृद्ध दृश्य कहानी",
        "Accepted: .wav, .mp3 • Upload a sample to begin scoring.": "स्वीकृत: .wav, .mp3 • स्कोरिंग शुरू करने के लिए एक नमूना अपलोड करें।",
        "AI Analysis Summary": "AI विश्लेषण सारांश",
        "Uploaded Audio Details": "अपलोड किए गए ऑडियो विवरण",
        "Format": "प्रारूप",
        "Size": "आकार",
        "Duration": "अवधि",
        "sec": "सेकंड",
        "Acoustic classification": "ध्वनिक वर्गीकरण",
        "Soil moisture trend": "मिट्टी की नमी की प्रवृत्ति",
        "Health Score": "स्वास्थ्य स्कोर",
        "AI soil health rating": "AI मृदा स्वास्थ्य रेटिंग",
        "AI Confidence": "AI विश्वसनीयता",
        "Model certainty": "मॉडल निश्चितता",
        "Soil Health Meter": "मृदा स्वास्थ्य मीटर",
        "Soil Technical Parameters": "मृदा तकनीकी पैरामीटर",
        "Moisture Level": "नमी का स्तर",
        "Compaction": "मिट्टी का संघनन",
        "Dryness": "सूखापन",
        "Acoustic Frequency": "ध्वनिक आवृत्ति",
        "Signal Energy": "सिग्नल ऊर्जा",
        "Scan Duration": "स्कैन अवधि",
        "Soil Sound Waveform": "मृदा ध्वनि तरंग रूप",
        "Extracted Audio Features": "निकाली गई ऑडियो विशेषताएं",
        "View as": "ऐसे देखें",
        "Bar chart": "बार चार्ट",
        "Line chart": "लाइन चार्ट",
        "Radar chart": "रडार चार्ट",
        "Feature Radar Summary": "विशेषता रडार सारांश",
        "Feature Trend Summary": "विशेषता प्रवृत्ति सारांश",
        "Value": "मान",
        "Feature Values": "विशेषता मान",
        "Current vs Ideal Parameters": "वर्तमान बनाम आदर्श पैरामीटर",
        "Parameter": "पैरामीटर",
        "Online": "ऑनलाइन",
        "Ask TerraEcho AI": "टेराइको AI से पूछें",
        "Chat with our AI agronomist assistant about soil aeration, crop cycles, or irrigation.": "मृदा वातन, फसल चक्र, या सिंचाई के बारे में हमारे AI कृषि विज्ञानी सहायक से चैट करें।",
        "My soil is compact. What should I do?": "मेरी मिट्टी सख्त है। मुझे क्या करना चाहिए?",
        "Ask TerraEcho": "टेराइको से पूछें",
        "TerraEcho Agronomist": "टेराइको कृषि विज्ञानी",
        "Download Soil Report PDF": "मृदा रिपोर्ट PDF डाउनलोड करें",
        
        # Reports
        "Reports & Exports": "रिपोर्ट और निर्यात",
        "Download investor-grade soil health reports and export your portfolio.": "निवेशक-ग्रेड मृदा स्वास्थ्य रिपोर्ट डाउनलोड करें और अपना पोर्टफोलियो निर्यात करें।",
        "Total Reports": "कुल रिपोर्ट",
        "Recent Run": "हालिया रन",
        "Export Entire Portfolio": "संपूर्ण पोर्टफोलियो निर्यात करें",
        "Download all generated soil reports in a single zip archive.": "एक ही ज़िप संग्रह में सभी उत्पन्न मिट्टी रिपोर्ट डाउनलोड करें।",
        "Prepare Report Bundle": "रिपोर्ट बंडल तैयार करें",
        "Download TerraEcho Report Bundle": "रिपोर्ट बंडल डाउनलोड करें",
        "Available Soil Reports": "उपलब्ध मृदा रिपोर्ट",
        "Sample Metadata": "नमूना मेटाडेटा",
        "Sample": "नमूना",
        "Unknown Location": "अज्ञात स्थान",
        "Analysis Result": "विश्लेषण परिणाम",
        "Download PDF": "PDF डाउनलोड करें",
        
        # AI Insights
        "AI Agronomy Insights": "AI कृषि अंतर्दृष्टि",
        "Deep soil acoustic intelligence for smarter agronomy and ecological health monitoring.": "स्मार्ट कृषि और पारिस्थितिक स्वास्थ्य निगरानी के लिए गहरी मिट्टी ध्वनिक बुद्धिमत्ता।",
        "Frequency Intelligence": "आवृत्ति इंटेलिजेंस",
        "Understand how sound spectral patterns map to soil moisture and compaction level variations.": "समझें कि ध्वनि वर्णक्रमीय पैटर्न मिट्टी की नमी और संघनन स्तर के विविधताओं से कैसे मेल खाते हैं।",
        "Crop Reflection": "फसल प्रतिबिंब",
        "Match agro-recommendations to the detected soil health profile for maximum crop yield potential.": "अधिकतम फसल उपज क्षमता के लिए खोजी गई मृदा स्वास्थ्य प्रोफ़ाइल के साथ कृषि सिफारिशों का मिलान करें।",
        "Sustainability Index": "स्थिरता सूचकांक",
        "Track regenerative farming signals through acoustic soil analysis and organic matter trends.": "ध्वनिक मिट्टी विश्लेषण और कार्बनिक पदार्थों के रुझान के माध्यम से पुनर्योजी कृषि संकेतों को ट्रैक करें।",
        "Health Score Distribution": "स्वास्थ्य स्कोर वितरण",
        "Historical Analysis Health Scores": "ऐतिहासिक विश्लेषण स्वास्थ्य स्कोर",
        "Collect soil samples to activate AI insight dashboards.": "AI अंतर्दृष्टि डैशबोर्ड को सक्रिय करने के लिए मिट्टी के नमूने एकत्र करें।",
        
        # History
        "Soil History": "मृदा इतिहास",
        "Review and compare past soil analyses performed in your workspace.": "अपने कार्यक्षेत्र में किए गए पिछले मिट्टी विश्लेषणों की समीक्षा और तुलना करें।",
        "Analysis Log": "विश्लेषण लॉग",
        "Notes": "टिप्पणियाँ",
        
        # About
        "About TerraEcho": "टेराइको के बारे में",
        "Built for farmers, researchers, NGOs, and agri-tech innovators focused on resilient soil systems.": "लचीली मिट्टी प्रणालियों पर ध्यान केंद्रित करने वाले किसानों, शोधकर्ताओं, गैर सरकारी संगठनों और कृषि-तकनीक नवप्रवर्तकों के लिए निर्मित।",
        "Mission": "मिशन",
        "Empower sustainable agriculture with accurate, easy-to-use soil health intelligence using acoustic resonance.": "ध्वनिक अनुनाद का उपयोग करके सटीक, उपयोग में आसान मृदा स्वास्थ्य समझ के साथ टिकाऊ कृषि को सशक्त बनाएं।",
        "Vision": "दृष्टि",
        "Transform soil scanning into fast, confident decisions for every field to enhance global crop security.": "वैश्विक फसल सुरक्षा बढ़ाने के लिए हर खेत के लिए त्वरित, आश्वस्त निर्णयों में मिट्टी की स्कैनिंग को बदलें।",
        "Values": "मूल्य",
        "Precision, environmental sustainability, technological accessibility, and measurable climate impact.": "सटीकता, पर्यावरणीय स्थिरता, तकनीकी पहुंच और मापने योग्य जलवायु प्रभाव।",
        "Get in Touch": "संपर्क करें",
        "Contact": "संपर्क",
        "Open Source": "ओपन सोर्स",
        "GitHub Repository": "गिटहब रिपॉजिटरी",
        "Eco Impact": "पर्यावरण प्रभाव",
        "Sustainability": "स्थिरता",
        "Supporting soil resilience, carbon sequestration, and climate-smart food networks.": "मिट्टी के लचीलेपन, कार्बन अवशोषण और जलवायु-स्मार्ट खाद्य नेटवर्क का समर्थन करना।"
    }
}

def t(key, lang="English"):
    return TRANSLATIONS.get(lang, TRANSLATIONS["English"]).get(key, key)
